### ISSUE TITLE
Semi-frequent CTD after saving, often causing duplication on the file (not corrupting)

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1192]
I am playing on Cata++ (correct version) and no other mod. The crash log is attached.
[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7756982/crash.log)
Edit: Debug.log added.
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7757243/debug.log)

**Comment by olanti-p** [comment]
May be caused by missing `act->set_to_null()` call when finishing an invalid `ACT_READ` activity.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/fe9f25b7f684f8d3ed41782efcea50c0e8c17e57/src/activity_handlers.cpp#L3168-L3171

**Comment by ghost** [comment]
Resolved via V2 save format. https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5777

feel free to re-open if this is reproducible on V2

**Comment by chaosvolt** [comment]
This still happens to me even with v2 save format, last encountered in build `2025-06-05`

Good news is I have a fix. If you check the save folder after this happens, you SHOULD see a .temp file with the same name as one of the other files in it. Deleting that file should undo the duplicate character, though obviously you'll lose whatever progress you made since the last time you saved prior to the crash.

**Comment by ghost** [comment]
Remember to mark as confirmed if you've reproduced an issue.
